import logging

logging.exception("aaa")
